### ISSUE TITLE
REGRESSION (0.4.0): assert_eq_hex with string argument doesn't compile

### ISSUE THREAD

**Issue by hortont424** [wcampbell0x2a/assert_hex#8]
error: 3 positional arguments in format string, but there are 2 arguments
    |
210 | ...   assert_eq_hex!(A, B, "string");
    |       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |

Because this line:

https://github.com/wcampbell0x2a/assert_hex/blob/fba9dbdd4413ee62b40d8366241142c93b922f00/src/lib.rs#L43

is missing a comma. And there's no test for assert_eq_hex with a string, only assert_ne_hex (which correctly has a comma).

**Comment by wcampbell0x2a** [comment]
Released a fix in https://github.com/wcampbell0x2a/assert_hex/releases/tag/v0.4.1
